"""Curated (non-AI) content for Voiladi: interests, prompts, icebreakers, cities."""

INTERESTS = [
    "Music", "Live gigs", "Hip-hop", "Indie", "K-pop", "Podcasts", "Photography", "Film", "Horror films",
    "Sitcoms", "Anime", "Gaming", "Board games", "Memes", "Reading", "Poetry", "Writing", "Art", "Museums",
    "Design", "Fashion", "Thrifting", "Sneakers", "Tattoos", "Gym", "Running", "Yoga", "Hiking", "Football",
    "Basketball", "Cricket", "Tennis", "Skateboarding", "Cycling", "Swimming", "Dancing", "Clubbing", "Cooking",
    "Baking", "Coffee", "Matcha", "Street food", "Vegan", "Travel", "Road trips", "Beach days", "Sunsets",
    "Camping", "Dogs", "Cats", "Plants", "Astrology", "Startups", "Coding", "Tech", "Volunteering", "Cars", "Bikes",
]

PROMPTS = [
    "My most irrational fear is",
    "The way to win me over is",
    "A perfect Sunday looks like",
    "I'm weirdly good at",
    "Two truths and a lie",
    "My go-to karaoke song is",
    "Green flag I look for",
    "I geek out on",
    "Unpopular opinion",
    "My simple pleasures",
    "Dating me is like",
    "Best travel story",
    "I'll fall for you if",
    "My current obsession",
    "The last thing that made me laugh",
    "Let's debate this",
]

ICEBREAKERS = [
    "Okay real talk: pineapple on pizza, yes or crime?",
    "What's one song you'd never skip?",
    "Rate your week out of 10. No explanation needed.",
    "Most underrated snack. Go.",
    "If we skipped small talk, what would you ask me?",
    "What's your comfort show right now?",
    "Beach sunrise or city midnight?",
    "Last thing that made you laugh out loud?",
    "Hot take: what's overrated?",
    "What's the story behind your first photo?",
    "Coffee, matcha, or chaos?",
    "Which of your interests would you teach me first?",
    "Sunday plan: brunch or a 2pm wake-up?",
    "Something you're weirdly competitive about?",
    "Most spontaneous thing you've done this year?",
    "Cats, dogs, or plants?",
    "What would your friends say your 'thing' is?",
    "A concert you'd time-travel for?",
    "Two-word review of your day.",
    "Best meal you've had this month?",
]

CITIES = [
    {"name": "New York", "country": "USA", "lat": 40.7128, "lng": -74.0060},
    {"name": "Los Angeles", "country": "USA", "lat": 34.0522, "lng": -118.2437},
    {"name": "San Francisco", "country": "USA", "lat": 37.7749, "lng": -122.4194},
    {"name": "Chicago", "country": "USA", "lat": 41.8781, "lng": -87.6298},
    {"name": "Miami", "country": "USA", "lat": 25.7617, "lng": -80.1918},
    {"name": "Austin", "country": "USA", "lat": 30.2672, "lng": -97.7431},
    {"name": "Seattle", "country": "USA", "lat": 47.6062, "lng": -122.3321},
    {"name": "Toronto", "country": "Canada", "lat": 43.6532, "lng": -79.3832},
    {"name": "Vancouver", "country": "Canada", "lat": 49.2827, "lng": -123.1207},
    {"name": "Mexico City", "country": "Mexico", "lat": 19.4326, "lng": -99.1332},
    {"name": "London", "country": "UK", "lat": 51.5074, "lng": -0.1278},
    {"name": "Manchester", "country": "UK", "lat": 53.4808, "lng": -2.2426},
    {"name": "Paris", "country": "France", "lat": 48.8566, "lng": 2.3522},
    {"name": "Berlin", "country": "Germany", "lat": 52.5200, "lng": 13.4050},
    {"name": "Amsterdam", "country": "Netherlands", "lat": 52.3676, "lng": 4.9041},
    {"name": "Barcelona", "country": "Spain", "lat": 41.3874, "lng": 2.1686},
    {"name": "Madrid", "country": "Spain", "lat": 40.4168, "lng": -3.7038},
    {"name": "Rome", "country": "Italy", "lat": 41.9028, "lng": 12.4964},
    {"name": "Milan", "country": "Italy", "lat": 45.4642, "lng": 9.1900},
    {"name": "Lisbon", "country": "Portugal", "lat": 38.7223, "lng": -9.1393},
    {"name": "Istanbul", "country": "Turkey", "lat": 41.0082, "lng": 28.9784},
    {"name": "Dubai", "country": "UAE", "lat": 25.2048, "lng": 55.2708},
    {"name": "Mumbai", "country": "India", "lat": 19.0760, "lng": 72.8777},
    {"name": "Delhi", "country": "India", "lat": 28.6139, "lng": 77.2090},
    {"name": "Bangalore", "country": "India", "lat": 12.9716, "lng": 77.5946},
    {"name": "Hyderabad", "country": "India", "lat": 17.3850, "lng": 78.4867},
    {"name": "Chennai", "country": "India", "lat": 13.0827, "lng": 80.2707},
    {"name": "Kolkata", "country": "India", "lat": 22.5726, "lng": 88.3639},
    {"name": "Pune", "country": "India", "lat": 18.5204, "lng": 73.8567},
    {"name": "Ahmedabad", "country": "India", "lat": 23.0225, "lng": 72.5714},
    {"name": "Jaipur", "country": "India", "lat": 26.9124, "lng": 75.7873},
    {"name": "Chandigarh", "country": "India", "lat": 30.7333, "lng": 76.7794},
    {"name": "Singapore", "country": "Singapore", "lat": 1.3521, "lng": 103.8198},
    {"name": "Tokyo", "country": "Japan", "lat": 35.6762, "lng": 139.6503},
    {"name": "Seoul", "country": "South Korea", "lat": 37.5665, "lng": 126.9780},
    {"name": "Bangkok", "country": "Thailand", "lat": 13.7563, "lng": 100.5018},
    {"name": "Jakarta", "country": "Indonesia", "lat": -6.2088, "lng": 106.8456},
    {"name": "Manila", "country": "Philippines", "lat": 14.5995, "lng": 120.9842},
    {"name": "Sydney", "country": "Australia", "lat": -33.8688, "lng": 151.2093},
    {"name": "Melbourne", "country": "Australia", "lat": -37.8136, "lng": 144.9631},
    {"name": "Lagos", "country": "Nigeria", "lat": 6.5244, "lng": 3.3792},
    {"name": "Nairobi", "country": "Kenya", "lat": -1.2921, "lng": 36.8219},
    {"name": "Cape Town", "country": "South Africa", "lat": -33.9249, "lng": 18.4241},
    {"name": "Sao Paulo", "country": "Brazil", "lat": -23.5505, "lng": -46.6333},
    {"name": "Buenos Aires", "country": "Argentina", "lat": -34.6037, "lng": -58.3816},
]

REPORT_REASONS = [
    "Fake profile or photos",
    "Inappropriate messages",
    "Inappropriate photos",
    "Underage",
    "Scam or spam",
    "Something else",
]
