package com.voiladi.app;

import android.app.Application;

/**
 * Application: Firebase auto-initialises from the google_app_id / gcm_defaultSenderId / project_id string resources
 * (generated by build_apk.py from firebase/google-services.json) through FirebaseInitProvider - nothing to do here
 * except make sure the notification channel exists before any push arrives.
 */
public class VoiladiApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Notifier.ensureChannel(this);
    }
}
